CODEX schema check
hubmapconsortium/ingest-validation-tests pull request #10
Opened 2022-03-09 20:56 UTC by mccalluc

I have not run this. If it's on my shoulders, I would take the time to add tests to this repo... but if you have some other way of checking it, great: I think it's in your court @jswelling to say what the next step should be.

2022-03-10 13:59 UTC, mruffalo commented
Thanks very much for jumping on this, @mccalluc -- and I should have mentioned that there's an [example metadata file](https://github.com/hubmapconsortium/codex-common-acquisition-metadata/blob/master/metadata_standard/1.0/experiment.json) in the same [directory](https://github.com/hubmapconsortium/codex-common-acquisition-metadata/tree/master/metadata_standard/1.0) as the schema, which I hope would be usable for unit testing.

2022-03-22 14:43 UTC, mruffalo requested changes

2022-03-22 14:43 UTC, mruffalo commented on src/ingest_validation_tests/codex_json_validator.py
> +        for glob_expr in ['**/[Ee]xperiment.json']:
After talking with @VasylVaskivskyi, this needs to be a different (new) filename, and we settled on `dataset.json`. I will make a PR to `ingest-validation-tools` to update the directory schema to match.

2022-03-22 16:24 UTC, mccalluc commented on src/ingest_validation_tests/codex_json_validator.py
> +        for glob_expr in ['**/[Ee]xperiment.json']:
pushed update

2022-04-05 15:50 UTC, mruffalo approved these changes

2022-04-08 17:32 UTC, jswelling reviewed
I think this gets applied to every file matching **/dataset.json regardless of assay type- is that really the intent?  @mruffalo Do you want to restrict this to just CODEX?

2022-04-08 17:41 UTC, jswelling commented
@mruffalo if you want to limit it to CODEX I think it's sufficient to just add:
```
    if not self.assay_type.lower() contains "codex":
        return
```
at the top of collect_errors().

2022-04-08 18:23 UTC, mruffalo commented
Thanks @jswelling -- it is the intention to limit this to only CODEX datasets. @mccalluc, I'm happy to push some changes to implement that, if you're okay with me adding commits to your branch/PR.

2022-04-08 18:31 UTC, mruffalo commented
I pushed a new branch [mruffalo/validate-codex-json-additions](https://github.com/hubmapconsortium/ingest-validation-tests/tree/mruffalo/validate-codex-json-additions) (just to err on the side of better PR etiquette), and I'm very happy to have those commits added to this PR if @mccalluc agrees.

2022-04-11 13:01 UTC, mccalluc commented
@mruffalo , thanks! I've made
- #11

from your branch... but CI failed? Re-running now, in case it's a fluke.

2022-04-18 13:11 UTC, mccalluc commented
Sorry for the noise: I think I'll close this, and then open a new PR on the same branch with only Joel as a reviewer. Going forward, I'm going to try not sending PR reminders, and we'll see how that goes.

2022-04-18 13:11 UTC, closed without merging